name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        nix_path: nixpkgs=channel:nixos-22.05
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - run: git clone https://github.com/dambaev/op-energy-development.git --recursive
    - run: mkdir ./private
    - run: nix-shell op-energy-development/overlays/op-energy/nix/shell.nix --run "./op-energy-development/overlays/op-energy/nix/gen-psk.sh ./private \"mainnet signet testnet\""
    - run: nix-build op-energy.nix