name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        nix_path: nixpkgs=channel:nixos-22.05
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - run: git clone https://github.com/dambaev/op-energy-development.git --recursive
    - run: cd op-energy-development && git checkout op-energy-dev-instance-dambaev && git submodule set-branch -b 300-implement-github-action-to-deploy-to-digital-ocean-when-pr-is-merged overlays/op-energy && git submodule update --remote
    - run: GITHUB_SHA=$(echo ${{ github.sha }} | cut -c 1-8) nix-build op-energy.nix --argstr GITHUB_SHA $GITHUB_SHA